### ISSUE TITLE
edizon cheat always active by default...

### ISSUE THREAD

**Issue by herman23a** [WerWolv/EdiZon#107]
even change cheat_enable_key = L,  still cannot make edizon cheat deactive by default

**Comment by WerWolv** [comment]
This is the default option so it doesn't have to depend purely on EdiZon to load it's cheats.
It can be fixed by opening the /atmosphere/config/system_settings.ini file in a normal text editor and changing 'dmnt_cheats_enabled_by_default = u8!0x1' to 'dmnt_cheats_enabled_by_default = u8!0x0' (without the quotes).
Next time you start a game now, all cheats will be disabled and you'll have to open EdiZon to activate the cheats you need.

**Comment by herman23a** [comment]
already set dmnt_cheats_enabled_by_default = u8!0x0
BUT still cheat active by default...

**Comment by steph9009** [comment]
this solution it doesn't work

**Comment by DogasNetwork** [comment]
indeed, it doesn't work!

**Comment by ghost** [comment]
doesnt work

**Comment by ResRipper** [comment]
For people can't get it working:

1. Copy `/atmosphere/config_templates/system_settings.ini` to `/atmosphere/config/`
2. Search for `dmnt_cheats_enabled_by_default` in `/atmosphere/config/system_settings.ini`
3. Change `; dmnt_cheats_enabled_by_default = u8!0x1` to `dmnt_cheats_enabled_by_default = u8!0x0`

Notice: `;` symbol in front means comment this whole line, some people might forget to remove it, which will cause this change to be unaffected
