### ISSUE TITLE
Cheats are automatically enabled

### ISSUE THREAD

**Issue by CommicKick69ing** [WerWolv/EdiZon#118]
Is there any setting or way to stop edizon for automatcaly enabling cheats?

**Comment by TechGeekGamer** [comment]
Quote from his Discord server
> This is the default option so it doesn't have to depend purely on EdiZon to load it's cheats.
It can be fixed by opening the /atmosphere/config/system_settings.ini file in a normal text editor and changing 'dmnt_cheats_enabled_by_default = u8!0x1' to 'dmnt_cheats_enabled_by_default = u8!0x0' (without the quotes). Make sure there's no semicolon ( ; ) in front of the setting!!
Next time you start a game now, all cheats will be disabled and you'll have to open EdiZon to activate the cheats you need.

**Comment by CommicKick69ing** [comment]
My ini file was u8!0x0 already for some reason and cheats are stil aautomatically enabled

**Comment by TechGeekGamer** [comment]
Did you move it to `atmosphere/config`?

**Comment by CommicKick69ing** [comment]
no

**Comment by TechGeekGamer** [comment]
Move it there and make sure to remove the semi-colon  in front of it

**Comment by CommicKick69ing** [comment]
I followed what you said but I cant get i to work

**Comment by CommicKick69ing** [comment]
nevermind it worked just had to reboot
