### ISSUE TITLE
cheats disabled by default

### ISSUE THREAD

**Issue by Vorffeed** [WerWolv/EdiZon#83]
Well ^ _ ^;
Is there any way for cheatsto be disabled by default and not enabled from the beginning?

**Comment by WerWolv** [comment]
This is the default option so Atmosphere doesn't have to depend purely on EdiZon to load it's cheats.
It can be fixed by opening the /atmosphere/system_settings.ini file in a normal text editor and changing 'dmnt_cheats_enabled_by_default = u8!0x1' to 'dmnt_cheats_enabled_by_default = u8!0x0' (without the quotes).
Next time you start a game now, all cheats will be disabled and you'll have to open EdiZon to activate the cheats you need.
