### ISSUE TITLE
Control's

### ISSUE THREAD

**Issue by hidekichanlee** [WerWolv/EdiZon#85]
I can't use the controls, just touch, because of that I can't update by pressing the 
"-"button.
 I'm using Atmosphère 0.9.4 with 9.0 fw
And last Edizon.
Because of that issue I still can't apply cheats.

**Comment by WerWolv** [comment]
The issue is that you're using Tinfoil/HBG or anything related to it. Their custom atmosphere fork breaks inputs in all homebrews that haven't been recompiled yet. I would suggest you to reinstall Kosmos/Atmosphere and stop using these homebrew but you can also try with the snapshot version here: https://github.com/WerWolv/EdiZon/releases/download/snapshot/EdiZon.nro It has been recompiled but it may have bugs in it
